package debop4s.data.mybatis

import debop4s.data.mybatis.mapping._
import debop4s.data.mybatis.session.Session
import org.slf4j.LoggerFactory

/**
 * DatabaseSchema
 * @author sunghyouk.bae@gmail.com 15. 3. 21.
 */
object DatabaseSchema {

  private val LOG = LoggerFactory.getLogger(getClass)

  def prepare(implicit session: Session): Unit = {
    LOG.info(s"create database schema...")
    createUserTable()
    LOG.info(s"done creation database!")
  }

  val createUserTable = new Perform {
    def xsql =
      <xsql>
        CREATE TABLE IF NOT EXISTS user(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
        name VARCHAR(64) NOT NULL,
        email VARCHAR(256) NOT NULL,
        PRIMARY KEY (id)
        )
      </xsql>
  }

  def bind = Seq(createUserTable)

}
