language: scala
script: sbt compile

scala:
  - 2.10.4
jdk:
  - oraclejdk7
services:
  - redis
env:
  - SBT_OPTS="-ea -server -Xmx8192m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"

# whitelist
branches:
  only:
    - develop