language: scala
script:
  - mvn ++$TRAVIS_SCALA_VERSION clean package

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'create database hibernate'

scala:
  - 2.10.4

jdk:
  - oraclejdk7
services:
  - redis
  - mongodb

env:
  - MAVEN_OPTS="-ea -server -Xmx2G -XX:PermSize=256M -XX:MaxPermSize=512M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"

# whitelist
branches:
  only:
    - develop