language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION test

scala:
  - 2.10.4
jdk:
  - oraclejdk7
services:
  - redis
  - mongodb
env:
  - SBT_OPTS="-ea -server -Xmx2G -XX:PermSize=256M -XX:MaxPermSize=512M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"

# whitelist
branches:
  only:
    - develop